### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by igarcia53** [blackboard-open-source/moodle-theme_snap#141]
Hello, I have installed snap in moodle 3.6 as it could show the messages.

when entering to message the page remains blank.

**Comment by MarcioQuimbundo** [comment]
the same here

**Comment by MarcioQuimbundo** [comment]
I fixed the bug

add this code inside layout > default.php in line 146, after closing div with id="page-content"

<?php echo $OUTPUT->standard_after_main_region_html() ?>

Good Lucky

**Comment by igarcia53** [comment]
Thanks......

**Comment by redesitos** [comment]
hello how are you, I have a problem, when accessing the url / message section, js messages are displayed that do not allow users to write messages.

  Failed to register / update a ServiceWorker in the scope 'https://moodle.url.com/message/': access to storage is restricted in this context due to user settings or private browsing mode. snap-ce.js: 1: 302914

Service worker registration failed with: DOMException: "The operation is insecure." snap-ce.js: 1: 302960

This happens with the last update of the theme in the moodle community with version 3.6

Thank you

**Comment by dvdcastro** [comment]
Hello,

We are no longer supporting Snap 3.6, feel free to replicate the issue and report again if it's happening for Snap 3.7.
